# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

'type: ci':
  - changed-files:
      - any-glob-to-any-file: .github/*
'component: autos':
  - changed-files:
      - any-glob-to-any-file: src/main/deploy/Choreo/**
      - any-glob-to-any-file: src/main/java/frc/robot/commands/**
'component: drivers':
  - changed-files:
      - any-glob-to-any-file: src/main/java/frc/robot/drivers/**

'subsystem: climb':
  - changed-files:
      - any-glob-to-any-file: src/main/java/frc/robot/subsystems/climb/**

'subsystem: intake':
  - changed-files:
      - any-glob-to-any-file: src/main/java/frc/robot/subsystems/feeder/**
      - any-glob-to-any-file: src/main/java/frc/robot/subsystems/indexer/**
      - any-glob-to-any-file: src/main/java/frc/robot/subsystems/intakepivot/**
      - any-glob-to-any-file: src/main/java/frc/robot/subsystems/intakerollers/**
'component: feeder':
  - changed-files:
      - any-glob-to-any-file: src/main/java/frc/robot/subsystems/feeder/**
'component: indexer':
  - changed-files:
      - any-glob-to-any-file: src/main/java/frc/robot/subsystems/indexer/**
'component: intake pivot':
  - changed-files:
      - any-glob-to-any-file: src/main/java/frc/robot/subsystems/intakepivot/**
'component: intake rollers':
  - changed-files:
      - any-glob-to-any-file: src/main/java/frc/robot/subsystems/intakerollers/**

'subsystem: shooter':
  - changed-files:
      - any-glob-to-any-file: src/main/java/frc/robot/subsystems/shooterpivot/**
      - any-glob-to-any-file: src/main/java/frc/robot/subsystems/shooter/**
      - any-glob-to-any-file: src/main/java/frc/robot/subsystems/turret/**
'component: shooter pivot':
  - changed-files:
      - any-glob-to-any-file: src/main/java/frc/robot/subsystems/shooterpivot/**
'component: shooter':
  - changed-files:
      - any-glob-to-any-file: src/main/java/frc/robot/subsystems/shooter/**
'component: turret':
  - changed-files:
      - any-glob-to-any-file: src/main/java/frc/robot/subsystems/turret/**

'subsystem: swerve':
  - changed-files:
      - any-glob-to-any-file: src/main/java/frc/robot/subsystems/swerve/**

'component: vision':
  - changed-files:
      - any-glob-to-any-file: src/main/java/frc/robot/subsystems/vision/**

'component: superstructure':
  - changed-files:
      - any-glob-to-any-file: src/main/java/frc/robot/subsystems/Superstructure.java

'type: utils':
  - changed-files:
      - any-glob-to-any-file: src/main/java/frc/robot/utils/**